"""Added tele handle

Revision ID: 0818d7a4c7ed
Revises: f95cd8f89355
Create Date: 2020-04-30 17:01:23.417095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0818d7a4c7ed'
down_revision = 'f95cd8f89355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('telegram_handle', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'telegram_handle')
    # ### end Alembic commands ###
