"""accept multiple requests

Revision ID: 3ecd14bb57e1
Revises: 9f1da5b4e3a8
Create Date: 2020-05-02 22:15:47.898410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ecd14bb57e1'
down_revision = '9f1da5b4e3a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('location_dropoffs', mysql.JSON(), nullable=True))
    op.drop_column('requests', 'location_dropoff')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('location_dropoff', mysql.VARCHAR(collation='utf8mb4_bin', length=250), nullable=True))
    op.drop_column('requests', 'location_dropoffs')
    # ### end Alembic commands ###
