"""Init

Revision ID: 9881e71bc7bc
Revises: 
Create Date: 2020-04-30 03:02:46.935500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9881e71bc7bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('additional_info', sa.String(length=250), nullable=True),
    sa.Column('location', mysql.JSON(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('package_type', sa.String(length=250), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'DONE', name='statetype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('additional_info', sa.String(length=250), nullable=True),
    sa.Column('location', mysql.JSON(), nullable=True),
    sa.Column('state', sa.Enum('ACTIVE', 'DONE', name='statetype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver_requests')
    op.drop_table('customer_requests')
    op.drop_table('blacklist')
    # ### end Alembic commands ###
