"""last updated

Revision ID: a606f8082b96
Revises: 18f500e67f81
Create Date: 2020-04-30 16:17:02.071906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a606f8082b96'
down_revision = '18f500e67f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'last_updated')
    # ### end Alembic commands ###
