"""Added names

Revision ID: f95cd8f89355
Revises: a606f8082b96
Create Date: 2020-04-30 16:42:16.148486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95cd8f89355'
down_revision = 'a606f8082b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('first_name', sa.String(length=250), nullable=True))
    op.add_column('requests', sa.Column('last_name', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'last_name')
    op.drop_column('requests', 'first_name')
    # ### end Alembic commands ###
